### ISSUE TITLE
TypeError: invalid rect assignment

### ISSUE THREAD

**Issue by rdansro** [Coopss/NMT-GameJam2016#1]
Traceback (most recent call last):
  File "RSI.py", line 1273, in <module>
    all_sprites.update()
  File "C:\Users\Robert\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pygame\sprite.py", line 462, in update
    s.update(*args)
  File "RSI.py", line 317, in update
    self.move()
  File "RSI.py", line 305, in move
    self.rect.y += self.speedy * abs(self.offsety / self.offsetx)
TypeError: invalid rect assignment

**Comment by ryanjcooper** [comment]
Solved

See https://github.com/Coopss/NMT-GameJam2016/pull/4
